---
services:
  # Main Services
  openreadmap:
    image: ghcr.io/webeng2/backend:main
    hostname: openreadmap
    ports:
      - '${OPENREADMAP_PORT}:8080'
    network_mode: "host" 
  
  redis:
    image: redis:latest
    hostname: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - ./db/redis:/data
    network_mode: "host" 

  mongo:
    image: mongo:latest
    hostname: mongodb
    restart: always
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASS}'
    volumes: 
      - ./db/mongo:/data/db
    network_mode: "host" 

  # Development Services 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGODB_USER}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGODB_PASS}'
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:${MONGODB_PORT}/'
      ME_CONFIG_BASICAUTH: false
    profiles: ['${MONGOEXPRESS_ENABLE}']
    network_mode: "host" 
