### GET request to hello world service
GET http://localhost:8080/hello
###

### POST request to hello world service
POST http://localhost:8080/hello
###

### GET request to user service
GET http://localhost:8080/user
###
